disabled_rules:
  - trailing_comma
  - identifier_name
  - type_name
  - opening_brace  # Conflicts with swift-format style for multi-line conditions

opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - vertical_whitespace_closing_braces

included:
  - Sources
  - Tests

excluded:
  - .build
  - Package.swift

line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000

nesting:
  type_level: 2
